[package]
name = "pee"
version = "0.1.0"
authors = ["Brainium Studios LLC"]
edition = "2018"
license = "LicenseRef-Brainium-Proprietary"

[dependencies]
gee = { git = "https://github.com/BrainiumLLC/gee" }
itertools = "0.9.0"
lyon_tessellation = "0.14.1"
