[package]
name = "pee"
version = "0.1.0"
authors = ["tyler <tyler@brainiumstudios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gee = { git = "https://github.com/BrainiumLLC/gee", features = ["euclid"] }
itertools = "0.8.0"
lyon_tessellation = "0.14.1"
